#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

mv log.simpleFoam log.simpleFoam-1
runParallel simpleFoam -postProcess -func 'cuts' -latestTime

#------------------------------------------------------------------------------
